# Generated by Django 4.2.11 on 2024-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0003_note_photo_trip_delete_adminreg_photo_trip_note_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
