# Generated by Django 4.2.11 on 2024-06-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0004_photo_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='static/photos/'),
        ),
    ]
