# Generated by Django 4.2.11 on 2024-06-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0005_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
    ]
